version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: pweb
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - .:/app

    ports:
      - "8000:8000"
    command: gunicorn pet_care.wsgi:application --bind 0.0.0.0:8000

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume:
