from django.db import models

# Create your models here.
from django.db import models

class Query(models.Model):
    """Model to store user queries"""
    text = models.TextField()
    is_pet_related = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    session_id = models.CharField(max_length=100)
    
    def __str__(self):
        return f"Query: {self.text[:50]}..."

class Question(models.Model):
    """Model to store follow-up questions generated by Gemini"""
    query = models.ForeignKey(Query, on_delete=models.CASCADE, related_name='questions')
    text = models.TextField()
    order = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Question {self.order}: {self.text[:50]}..."
    
    class Meta:
        ordering = ['order']

class Answer(models.Model):
    """Model to store user answers to follow-up questions"""
    question = models.OneToOneField(Question, on_delete=models.CASCADE, related_name='answer')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Answer to Q{self.question.order}: {self.text[:50]}..."

class Remedy(models.Model):
    """Model to store remedies generated by Gemini"""
    query = models.OneToOneField(Query, on_delete=models.CASCADE, related_name='remedy')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Remedy for {self.query.text[:30]}: {self.text[:50]}..."